### ISSUE TITLE
Doors Script

### ISSUE THREAD

**Issue by Jannatul89sInGithub** [RegularVynixu/Vynixius#16]
Vynixu. Doors/Script.lua isn't working anymore. The settings don't show anymore, the gui is blank. it doesn't show the options anymore. Vynixu you gotta fix this, your script was sooooo good. I favored it more than other scripts.

**Comment by RegularVynixu** [comment]
I am very glad to hear you liked the script. Although I will have to inform you that Vynixius has been discontinued as of a few months ago and all scripts included are now deprecated.
