### ISSUE TITLE
Reason For Ban (North#8354)

### ISSUE THREAD

**Issue by northjmhibjb** [RegularVynixu/Vynixius#2]
Sorry to leave a issue, only way I can get any sort of information, today I was trying to find the server but I was banned, Ive been in the server for a very very long time without any occurences of breaking any rules, I just want the reason I was banned including why I was banned and If it was a message or something as I got token logged a few days ago.

**Comment by the-one-with-raspberry** [comment]
discord.gg/vynixius is not made by vynixu
