### ISSUE TITLE
Rush Avoidance Broken

### ISSUE THREAD

**Issue by xzyq2** [RegularVynixu/Vynixius#4]
So the script detects if rush exists and teleports you up a some studs to avoid it but when you are in a room that is entered by stairs, it does not teleport you up because it thinks you are already high enough to not be killed by rush.
![image](https://user-images.githubusercontent.com/105599049/190876764-47d818bb-f0a9-4446-be94-d67b49110a29.png)

**Comment by xzyq2** [comment]
You might be able to fix this by having the script get the player's Z axis and then adding the studs to it then teleport to that Z axis instead of teleporting the player to a fixed Z axis

**Comment by RegularVynixu** [comment]
Thank you for taking the time to write out an issue ticket. Although Vynixius now has been discontinued.
