### ISSUE TITLE
[Request] Apeirophobia Script

### ISSUE THREAD

**Issue by 0Ariel0** [RegularVynixu/Vynixius#5]
I was looking at your scripts, when I saw you made one of "Doors". So I wanted to ask for a script about Apeirophobia because it is very annoying to get things done, and I wanted at least a general esp that would help a lot.

**Comment by RegularVynixu** [comment]
I appreciate the game suggestion, and apologies for the late reply. But I have to inform you that Vynixius has been discontinued as of a few months ago and all the scripts included are now deprecated.
