### ISSUE TITLE
Autocomplete library and Auto hang paintings not working

### ISSUE THREAD

**Issue by rocord01** [RegularVynixu/Vynixius#6]
The **Autocomplete library** and the **Auto hang paintings** options do not work in the doors script. They try to complete their task, but they end up having you stuck in the top center of the room.

**Comment by the-one-with-raspberry** [comment]
there's no option for that, right?

**Comment by RegularVynixu** [comment]
Thank you for taking the time to report an issue, and apologies for the late reply. But I have to inform you that Vynixius has been discontinued as of a few months ago and all the scripts included are now deprecated.
