### ISSUE TITLE
Script doesnt work at Rooms

### ISSUE THREAD

**Issue by Domates5** [RegularVynixu/Vynixius#8]
i opened script at doors then i go rooms then script doesnt work

**Comment by rocord01** [comment]
Are you using the auto [auto loader](https://github.com/RegularVynixu/Vynixius/blob/main/Doors/Loader.lua)  for each game?

**Comment by Domates5** [comment]
no i dont.

**Comment by aern320** [comment]
how do i download the script

**Comment by FanaticExplorer** [comment]
> how do i download the script

just write in your injector editor this:
`loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Doors/Loader.lua"))()`
inject, and when you are in run (not in lobby), execute it
